baseURL = 'http://industria4-0.infenlaces.com/'
# languageCode = 'es-ES'
title = 'Automatización del aula 2.09'
theme='docsy'




# Para poder cargar emogin https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true


#Establecer el idioma predeterminado
# defaultContentLanguage="es"



# Para crear gráficos direccionales
[params.markmap]
    enable = true

#Parámetros para que trabaje mermaid
 [params.mermaid]
enable = true
#Menus



[menu]
[[menu.main]]
  name = 'Wikieducator'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'

[[menu.main]]
  name = 'Slack'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
[[menu.main]]
  name = 'Git'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
[[menu.main]]
  name = 'Trello'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'



#Vamos a especificar las imágenes

#Links aparecen en el footer de la página
[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "http://webmail.industria4-0.infenlaces.com/"
	icon = "fa fa-envelope"
        desc = "Cuaquier aprotación será bienvenida"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"