baseURL = 'http://manuel.infenlaces.com/industria4-0/presentacion'
# languageCode = 'es-ES'
title = 'Automatizaci칩n del aula 2.09'
theme='docsy'




# Para poder cargar emogin https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true

#Establecer el idioma predeterminado
# defaultContentLanguage="es"


# Para crear gr치ficos direccionales
[params.markmap]
    enable = true
#Par치metros para que trabaje mermaid
 [params.mermaid]
enable = true

#Vamos a especificar las im치genes
